export const FALLBACK_RESOURCES = [
  {
    id: 1,
    name: 'Aurora Boardroom',
    type: 'room',
    description: 'Executive boardroom with panoramic 4K display, immersive audio and conference-grade lighting.',
    capacity: 12,
    location: 'Floor 4',
    avail_start: 8,
    avail_end: 20,
    requires_approval: true,
    department_restricted: '',
    max_duration_min: 240,
    active: true,
    image_url: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&q=80',
    scene_type: 'large',
    amenities: 'wifi,display,sound,projector,chairs',
    hourly_cost: 50,
  },
  {
    id: 2,
    name: 'Titan Conference Hall',
    type: 'room',
    description: 'Large-capacity hall for company-wide town-halls, client pitches and training sessions.',
    capacity: 20,
    location: 'Floor 5',
    avail_start: 8,
    avail_end: 20,
    requires_approval: true,
    department_restricted: '',
    max_duration_min: 240,
    active: true,
    image_url: 'https://images.unsplash.com/photo-1431540015161-0bf868a2d407?w=1200&q=80',
    scene_type: 'large',
    amenities: 'wifi,display,sound,projector,chairs,parking',
    hourly_cost: 50,
  },
  {
    id: 3,
    name: 'Quantum Lab',
    type: 'room',
    description: 'Innovation lab with writable walls, standing desks and dev monitors.',
    capacity: 8,
    location: 'Floor 3',
    avail_start: 8,
    avail_end: 20,
    requires_approval: true,
    department_restricted: '',
    max_duration_min: 240,
    active: true,
    image_url: 'https://images.unsplash.com/photo-1562774053-701939374585?w=1200&q=80',
    scene_type: 'medium',
    amenities: 'wifi,display,sound,chairs',
    hourly_cost: 50,
  },
  {
    id: 4,
    name: 'Orbit Huddle Space',
    type: 'room',
    description: 'Cozy huddle room for brainstorming, sprint planning and design reviews.',
    capacity: 6,
    location: 'Floor 2',
    avail_start: 8,
    avail_end: 20,
    requires_approval: false,
    department_restricted: '',
    max_duration_min: 240,
    active: true,
    image_url: 'https://images.unsplash.com/photo-1517502884422-41eaead166d4?w=1200&q=80',
    scene_type: 'medium',
    amenities: 'wifi,display,chairs',
    hourly_cost: 50,
  },
  {
    id: 5,
    name: 'Nova Meeting Room',
    type: 'room',
    description: 'Standard meeting room with a circular conference table and modern AV setup.',
    capacity: 8,
    location: 'Floor 2',
    avail_start: 8,
    avail_end: 20,
    requires_approval: false,
    department_restricted: '',
    max_duration_min: 240,
    active: true,
    image_url: 'https://images.unsplash.com/photo-1604328698692-f76ea9498e76?w=1200&q=80',
    scene_type: 'normal',
    amenities: 'wifi,display,sound,chairs',
    hourly_cost: 50,
  },
  {
    id: 6,
    name: 'Helix Collaboration Room',
    type: 'room',
    description: 'Collaborative meeting space with glass walls and ergonomic seating for 8.',
    capacity: 8,
    location: 'Floor 3',
    avail_start: 8,
    avail_end: 20,
    requires_approval: false,
    department_restricted: '',
    max_duration_min: 240,
    active: true,
    image_url: 'https://images.unsplash.com/photo-1517502884422-41eaead166d4?w=1200&q=80',
    scene_type: 'normal',
    amenities: 'wifi,display,sound,chairs',
    hourly_cost: 50,
  },
  {
    id: 7,
    name: 'Nebula Focus Pod',
    type: 'room',
    description: 'Soundproof 1-on-1 collaboration pod with integrated display and acoustic panels.',
    capacity: 2,
    location: 'Floor 2',
    avail_start: 8,
    avail_end: 20,
    requires_approval: false,
    department_restricted: '',
    max_duration_min: 240,
    active: true,
    image_url: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=1200&q=80',
    scene_type: 'cabin',
    amenities: 'wifi,display,chairs',
    hourly_cost: 50,
  },
  {
    id: 8,
    name: 'Zenith Focus Cabin',
    type: 'room',
    description: 'Premium focus cabin for deep-work, interviews or 1:1 mentorship sessions.',
    capacity: 2,
    location: 'Floor 4',
    avail_start: 8,
    avail_end: 20,
    requires_approval: false,
    department_restricted: '',
    max_duration_min: 240,
    active: true,
    image_url: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=1200&q=80',
    scene_type: 'cabin',
    amenities: 'wifi,display,chairs',
    hourly_cost: 50,
  },
  {
    id: 9,
    name: 'Executive Cabin — Summit',
    type: 'room',
    description: 'Private executive cabin with plush seating and floor-to-ceiling windows.',
    capacity: 4,
    location: 'Floor 6',
    avail_start: 8,
    avail_end: 20,
    requires_approval: true,
    department_restricted: '',
    max_duration_min: 240,
    active: true,
    image_url: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&q=80',
    scene_type: 'manager',
    amenities: 'wifi,display,sound,chairs,parking',
    hourly_cost: 50,
  },
  {
    id: 10,
    name: 'Galaxy War Room',
    type: 'room',
    description: 'Executive strategy cabin with private workstations and presentation screens.',
    capacity: 6,
    location: 'Floor 6',
    avail_start: 8,
    avail_end: 20,
    requires_approval: true,
    department_restricted: '',
    max_duration_min: 240,
    active: true,
    image_url: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=1200&q=80',
    scene_type: 'manager',
    amenities: 'wifi,display,sound,projector,chairs',
    hourly_cost: 50,
  },
  {
    id: 11,
    name: 'Chess Lounge',
    type: 'recreation',
    description: 'Quiet chess lounge with two premium chess boards, analog clocks and leather armchairs. Open to everyone — no approval needed.',
    capacity: 4,
    location: 'Floor 1 · Recreation Wing',
    avail_start: 8,
    avail_end: 20,
    requires_approval: false,
    department_restricted: '',
    max_duration_min: 240,
    active: true,
    image_url: 'https://images.unsplash.com/photo-1560174038-594a18c76bc1?w=1200&q=80',
    scene_type: 'chess',
    amenities: 'wifi,chairs',
    hourly_cost: 50,
  },
  {
    id: 12,
    name: 'Foosball Arena',
    type: 'recreation',
    description: 'Championship-grade foosball table with LED scoreboard. Great for quick breaks and team bonding.',
    capacity: 4,
    location: 'Floor 1 · Recreation Wing',
    avail_start: 8,
    avail_end: 20,
    requires_approval: false,
    department_restricted: '',
    max_duration_min: 240,
    active: true,
    image_url: 'https://images.unsplash.com/photo-1611195974226-a6a9be9dd763?w=1200&q=80',
    scene_type: 'foosball',
    amenities: 'wifi,sound',
    hourly_cost: 50,
  },
]

export const findFallbackResource = (id) =>
  FALLBACK_RESOURCES.find((resource) => String(resource.id) === String(id))
